services:
  n5challenge:
    image: n5challenge
    build:
      context: .
      dockerfile: N5Challenge/Dockerfile

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=n5ch4ll3ng3!
    ports:
      - "1433:1433"
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.9.1
    restart: unless-stopped
    hostname: kafka
    container_name: kafka
    ports:
      - 9091:9091
      - 9092:9092
      - 9093:9093
    volumes:
      - ./storage/kafka:/tmp/kraft-combined-logs
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NODE_ID: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: '1ofeTjqtTaiTp-EB1-k-UQ'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: 'CONTROLLER://0.0.0.0:9093,INTERNAL://0.0.0.0:9092,INTERNALUI://0.0.0.0:9091'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,INTERNALUI:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://localhost:9092,INTERNALUI://kafka:9091'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
    networks:
      viridian.ltd:
        aliases:
          - kafka.viridian.ltd